"""initial

Revision ID: d40343058905
Revises: 
Create Date: 2021-09-04 23:12:38.518625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40343058905'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submodule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('functions', sa.JSON(), nullable=False),
    sa.Column('min_module_version', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('files_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installation',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('installation_date', sa.DateTime(), nullable=False),
    sa.Column('submodule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submodule_id'], ['submodule.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installation')
    op.drop_table('submodule')
    op.drop_table('secrets')
    # ### end Alembic commands ###
