name: Linters
on: pull_request


jobs:

   flake8:
     runs-on: ubuntu-latest
     steps:
       -  uses: actions/checkout@v2
          with:
            submodules: recursive
       - name: "Install Requirement"
         run: |
          pip3 install flake8
       - name: "Run linter"
         run: |
          flake8 ./
