name: Tests
on: pull_request


jobs:

   pytest:
     runs-on: ubuntu-latest
     steps:
       -  uses: actions/checkout@v2
          with:
            submodules: recursive
       - name: "Install Requirement"
         run: |
          pip3 install -r requirements-dev.txt
       - name: "Run tests"
         run: |
            pytest -v
