name: Dockerhub
on: 
  push:
    branches:
      - dev
      - test
      - CICD-16
jobs:

   Dockerhub:
     runs-on: ubuntu-latest
     steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Publish on Docker hub
        run: |
          docker build -t restbase/restbase-server:$(cat VERSION)-${{ steps.extract_branch.outputs.branch }} .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push restbase/restbase-server:$(cat VERSION)-${{ steps.extract_branch.outputs.branch }}
