name: DeployBranchPipeline
on:
  push:
    branches:
      - dev
      - test
jobs:
   pytest:
     runs-on: ubuntu-latest
     steps:
       -  uses: actions/checkout@v2
          with:
            submodules: recursive
       - name: "Install Requirement"
         run: |
          pip3 install -r requirements-dev.txt
       - name: "Run tests"
         run: |
            pytest -v

   Dockerhub:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Publish on Docker hub
        run: |
          docker build -t restbase/restbase-server:$(cat VERSION)-${{ steps.extract_branch.outputs.branch }} .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push restbase/restbase-server:$(cat VERSION)-${{ steps.extract_branch.outputs.branch }}
